
export const DISPLAY_BY_LABS = "DISPLAY_BY_LABS";
export const EDIT_DATA_LABS = "EDIT_DATA_LABS";
export const SHOW_EDIT_PROFILE = "SHOW_EDIT_PROFILE";
export const SHOW_STATS_BY_PROFILE = "SHOW_STATS_BY_PROFILE";